#!/usr/bin/env python3
"""
Generate src/WebPage_gz.h — the web UI, gzipped, as a byte array.

Why: the plain-text page is ~59 KB of the firmware image, and with flash at 80 %
that is the single largest recoverable block. HTML compresses roughly 5x, and
every browser sends `Accept-Encoding: gzip`, so serving it pre-compressed with
`Content-Encoding: gzip` costs nothing at runtime — no CPU, no RAM, the ESP32
just sends the bytes it already has.

Run from the webpage/ directory after editing index.html:

    python webpage_gz_generator.py

webpage/ is the source of truth, the header under src/ is generated. Do not
hand-edit the generated file — that drift has already bitten once.
"""

import gzip
import io
import os
import sys

# (source file, C identifier). Order only affects the generated file's layout.
ASSETS = [
    ("index.html", "index_html"),
    ("styles.css", "styles_css"),   # generated by `npm run build`
]

OUT = os.path.join("..", "src", "WebPage_gz.h")

HEADER = """/**
   @file WebPage_gz.h

   @brief GENERATED FILE - do not edit by hand.

   Web assets pre-compressed with gzip and served with `Content-Encoding: gzip`.
   Regenerate with:  cd webpage && python webpage_gz_generator.py

   Sources of truth live in webpage/. Editing this file directly will be silently
   overwritten on the next regeneration.
*/

#pragma once

#include <stdint.h>
#include <stddef.h>

"""


def compress(raw):
    """gzip `raw` with the mtime field zeroed.

    gzip.compress() stamps the current time into the header, so regenerating an
    unchanged source still produced a diff on four bytes of every array. Pinning
    mtime makes the output a pure function of the input, which is what lets
    `git diff` after a regeneration mean something.
    """
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode="wb", compresslevel=9, mtime=0) as fh:
        fh.write(raw)
    return buf.getvalue()


def emit(fh, name, raw):
    comp = compress(raw)
    fh.write(f"/* {name}: {len(raw)} B raw -> {len(comp)} B gzip "
             f"({100.0 * len(comp) / len(raw):.1f}%) */\n")
    fh.write(f"const uint8_t {name}_gz[] PROGMEM = {{\n")
    for i in range(0, len(comp), 16):
        row = ", ".join(f"0x{b:02x}" for b in comp[i:i + 16])
        fh.write(f"  {row},\n")
    fh.write("};\n")
    fh.write(f"const size_t {name}_gz_len = {len(comp)};\n\n")
    return len(raw), len(comp)


def main():
    if not os.path.isfile("index.html"):
        sys.exit("error: run this from the webpage/ directory")

    total_raw = total_gz = 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(HEADER)
        for src, name in ASSETS:
            if not os.path.isfile(src):
                sys.exit(f"error: {src} is listed in ASSETS but missing")
            with open(src, "rb") as f:
                raw = f.read()
            r, c = emit(fh, name, raw)
            total_raw += r
            total_gz += c
            print(f"  {src:<26} {r:>7} -> {c:>7} B")

    saved = total_raw - total_gz
    print(f"\n  total {total_raw} -> {total_gz} B  (saved {saved} B / {saved / 1024:.1f} KB)")
    print(f"  wrote {OUT}")


if __name__ == "__main__":
    main()
